language: node_js

node_js:
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

script:
    - node mksnapshot.js ~/work/mksnapshot/test/fixtures/snapshot.js
    - node mksnapshot.js ~/work/mksnapshot/test/fixtures/invalid.js
    - npm test
